-- Test Companies for FANTACER
-- Execute in Supabase SQL Editor
-- These are TEST data - replace with real companies

INSERT INTO companies (name, category, description) VALUES
('TechnoVision Srl', 'Technology', 'Innovative tech solutions'),
('GreenEnergy SpA', 'Energy', 'Renewable energy provider'),
('FinanceHub Italia', 'Finance', 'Financial consulting'),
('MediCare Plus', 'Health', 'Healthcare services'),
('FoodTaste Corp', 'Food', 'Premium food products'),
('RetailMasters', 'Retail', 'Retail chain'),
('LogiFast Srl', 'Logistics', 'Logistics & shipping'),
('BuildRight Construction', 'Construction', 'Construction company'),
('AutoDrive Italia', 'Automotive', 'Auto dealer'),
('TravelEasy Agency', 'Tourism', 'Travel agency'),
('EduLearn Institute', 'Education', 'Education services'),
('SportFit Club', 'Sport', 'Sports center'),
('FashionStyle Spa', 'Fashion', 'Fashion brand'),
('MediaChannel Italia', 'Media', 'Media company'),
('AgriGreen Farm', 'Agriculture', 'Organic farm'),
('TechCloud Solutions', 'Technology', 'Cloud services'),
('CyberSecure Corp', 'Technology', 'Cybersecurity'),
('DataWave Analytics', 'Technology', 'Data analytics'),
('AIoT Innovation', 'Technology', 'IoT solutions'),
('Blockchain Tech', 'Technology', 'Blockchain services'),
('QuantumComputing', 'Technology', 'Quantum computing'),
('NanoTech Lab', 'Technology', 'Nanotechnology'),
('BioTech Pharma', 'Health', 'Pharmaceutical'),
('MedRobotics', 'Health', 'Medical robots'),
('HealthAI Systems', 'Health', 'Health AI'),
('EcoGreen Energy', 'Energy', 'Eco energy'),
('SolarPower Italia', 'Energy', 'Solar energy'),
('WindForce Corp', 'Energy', 'Wind energy'),
('HydroTech Solutions', 'Energy', 'Hydro power'),
('BioGas Industries', 'Energy', 'Biogas production'),
('SmartGrid Italia', 'Energy', 'Smart grid'),
('BankingTech', 'Finance', 'Fintech'),
('PayTech Solutions', 'Finance', 'Payment solutions'),
('CryptoVault', 'Finance', 'Crypto services'),
('InsureTech Corp', 'Finance', 'Insurtech'),
('WealthManage Italia', 'Finance', 'Wealth management'),
('LeaseFlow Auto', 'Finance', 'Auto leasing'),
('TradeFinance Global', 'Finance', 'Trade finance'),
('CoinExchange', 'Finance', 'Crypto exchange'),
('BondMarket Italia', 'Finance', 'Bond trading'),
('StockInvest Corp', 'Finance', 'Stock investment'),
('VentureCapital Italia', 'Finance', 'VC firm'),
('PrivateEquity Group', 'Finance', 'Private equity'),
('FoodChain Supply', 'Food', 'Food supply'),
('OrganicFarm Italia', 'Food', 'Organic products'),
('WineEstate Tuscany', 'Food', 'Wine producer'),
('CheeseArtisan', 'Food', 'Artisan cheese'),
('Pastifico Romano', 'Food', 'Pasta maker'),
('Oliveto Italiano', 'Food', 'Olive oil'),
('Trattoria Chain', 'Food', 'Restaurant chain'),
('CateringPremium', 'Food', 'Catering services'),
('SuperBio Market', 'Food', 'Organic supermarket'),
('CoffeeRoasters Italia', 'Food', 'Coffee roaster'),
('TeaGarten Italia', 'Food', 'Tea importer'),
('BeerCraft Brewery', 'Food', 'Craft beer'),
('DistilleryItalia', 'Food', 'Distillery'),
('ChocolateFactory', 'Food', 'Chocolate maker'),
('IceCream Parlor', 'Food', 'Ice cream'),
('BakeryArtisan', 'Food', 'Artisan bakery'),
('Pizzeria Napoli', 'Food', 'Pizza chain'),
('SushiMaster Italia', 'Food', 'Sushi restaurant'),
('BurgerKingDom', 'Food', 'Fast food'),
('HealthyFood Corp', 'Food', 'Healthy meals'),
('PhytoCare Pharma', 'Health', 'Pharma'),
('DentalCare Plus', 'Health', 'Dental clinic'),
('OptiVision Eye', 'Health', 'Eye care'),
('PhysioTherapy Center', 'Health', 'Physiotherapy'),
('PsychoWellness', 'Health', 'Psychology'),
('FitGym Italia', 'Sport', 'Gym chain'),
('YogaSpace Studio', 'Sport', 'Yoga studio'),
('SwimAcademy', 'Sport', 'Swimming school'),
('TennisClub Italia', 'Sport', 'Tennis club'),
('GolfResort Italia', 'Sport', 'Golf resort'),
('CyclingTeam Pro', 'Sport', 'Cycling team'),
('RunningClub', 'Sport', 'Running club'),
('MountainBike Italia', 'Sport', 'MTB'),
('SkiAcademy', 'Sport', 'Ski school'),
('MartialArts Center', 'Sport', 'Martial arts'),
('DanceStudio Pro', 'Sport', 'Dance studio'),
('PilatesCore', 'Sport', 'Pilates'),
('CrossFit Italia', 'Sport', 'CrossFit'),
('BoxeItaliana', 'Sport', 'Boxing'),
('SailingClub', 'Sport', 'Sailing'),
('DivingCenter', 'Sport', 'Diving'),
('FashionHouse Milano', 'Fashion', 'Fashion house'),
('ShoeDesigner Italia', 'Fashion', 'Shoes'),
('BagLuxury', 'Fashion', 'Luxury bags'),
('JewelArtisan', 'Fashion', 'Jewelry'),
('WatchMaker Italia', 'Fashion', 'Watches'),
('PerfumeFactory', 'Fashion', 'Perfumes'),
('TailorSartoria', 'Fashion', 'Tailoring'),
('Bespoke Italia', 'Fashion', 'Bespoke suits'),
('KidsFashion', 'Fashion', 'Children wear'),
('SportStyle', 'Fashion', 'Sportswear'),
('AccessoryLux', 'Fashion', 'Accessories'),
('HatDesigner', 'Fashion', 'Hats'),
('ScarfArtisan', 'Fashion', 'Scarves'),
('GloveFactory', 'Fashion', 'Gloves'),
('BeltMaker Italia', 'Fashion', 'Belts'),
('CosmeticsLab', 'Beauty', 'Cosmetics'),
('SpaWellness Center', 'Beauty', 'Spa'),
('NailArt Studio', 'Beauty', 'Nail art'),
('HairStyle Pro', 'Beauty', 'Hair salon'),
('MakeupAcademy', 'Beauty', 'Makeup school'),
('BarberShop Italia', 'Beauty', 'Barber'),
('Perfumeria Art', 'Beauty', 'Perfume store'),
('SkinCare Clinic', 'Beauty', 'Dermatology'),
('YogaWellness', 'Wellness', 'Yoga wellness'),
('WellnessCenter Spa', 'Wellness', 'Wellness center'),
('MeditationHub', 'Wellness', 'Meditation'),
('AromaTherapy', 'Wellness', 'Aromatherapy'),
('MassageTherapy', 'Wellness', 'Massage'),
('SpaResort Italia', 'Wellness', 'Spa resort'),
('DetoxCenter', 'Wellness', 'Detox'),
('NaturalHealing', 'Wellness', 'Natural healing'),
('HolisticHealth', 'Wellness', 'Holistic'),
('MindfulnessCenter', 'Wellness', 'Mindfulness'),
('ZenGarden Italia', 'Wellness', 'Zen center'),
('RetreatWellness', 'Wellness', 'Retreat'),
('NatureCure', 'Wellness', 'Nature cure'),
('ConsultingPro', 'Consulting', 'Consulting'),
('StrategyAdvisors', 'Consulting', 'Strategy'),
('ManagementConsult', 'Consulting', 'Management'),
('AuditPartners', 'Consulting', 'Audit'),
('TaxLegalConsult', 'Consulting', 'Tax legal'),
('HRConsulting', 'Consulting', 'HR consulting'),
('LegalTech', 'Consulting', 'Legal tech'),
('PatentAttorney', 'Consulting', 'Patents'),
('ComplianceCorp', 'Consulting', 'Compliance'),
('RiskManagement', 'Consulting', 'Risk'),
('BusinessConsult', 'Consulting', 'Business'),
('CorporateAdvisors', 'Consulting', 'Corporate'),
('ExecutiveCoach', 'Consulting', 'Executive coaching'),
('CareerCounsel', 'Consulting', 'Career counseling'),
('RealEstateDev', 'Real Estate', 'Real estate'),
('PropertyGroup', 'Real Estate', 'Property'),
('EstateAgents', 'Real Estate', 'Estate agents'),
('PropertyManage', 'Real Estate', 'Property management'),
('ConstructionCorp', 'Real Estate', 'Construction'),
('ArchitecturePro', 'Real Estate', 'Architecture'),
('InteriorDesign', 'Real Estate', 'Interior design'),
('HomeStaging', 'Real Estate', 'Home staging'),
('FacilityManage', 'Real Estate', 'Facility management'),
('PropertyTech', 'Real Estate', 'PropTech'),
('SmartHome Italia', 'Real Estate', 'Smart home'),
('BuildingMaterials', 'Real Estate', 'Materials'),
('HardwareStore', 'Retail', 'Hardware'),
('FurnitureHub', 'Retail', 'Furniture'),
('ElectronicsStore', 'Retail', 'Electronics'),
('ClothingStore', 'Retail', 'Clothing'),
('GroceryChain', 'Retail', 'Grocery'),
('ConvenienceStore', 'Retail', 'Convenience'),
('SuperMarket Plus', 'Retail', 'Supermarket'),
('PharmacyChain', 'Retail', 'Pharmacy'),
('PetStore Italia', 'Retail', 'Pet store'),
('ToyStore Italia', 'Retail', 'Toys'),
('BookStore Chain', 'Retail', 'Books'),
('MusicStore', 'Retail', 'Music'),
('GameStore Italia', 'Retail', 'Gaming'),
('SportStore', 'Retail', 'Sports retail'),
('BikeStore', 'Retail', 'Bikes'),
('OutdoorStore', 'Retail', 'Outdoor'),
('GardenCenter', 'Retail', 'Garden'),
('FlowersShop', 'Retail', 'Flowers'),
('GiftStore', 'Retail', 'Gifts'),
('JewelryStore', 'Retail', 'Jewelry'),
('WatchStore', 'Retail', 'Watches'),
('ShoeStore', 'Retail', 'Shoes'),
('BagStore', 'Retail', 'Bags'),
('OpticalStore', 'Retail', 'Optical'),
('ElectronicsPlus', 'Technology', 'Electronics'),
('ComputerShop', 'Technology', 'Computers'),
('PhoneStore', 'Technology', 'Phones'),
('TabletStore', 'Technology', 'Tablets'),
('GadgetStore', 'Technology', 'Gadgets'),
('SmartphoneRepair', 'Technology', 'Repair'),
('WebDesign Pro', 'Technology', 'Web design'),
('AppDeveloper', 'Technology', 'Apps'),
('SoftwareHouse', 'Technology', 'Software'),
('CloudServices', 'Technology', 'Cloud'),
('DataCenter', 'Technology', 'Data center'),
('NetworkSolutions', 'Technology', 'Networking'),
('TelecomItalia', 'Telecom', 'Telecom'),
('PhoneOperator', 'Telecom', 'Mobile operator'),
('InternetProvider', 'Telecom', 'ISP'),
('SatelliteCom', 'Telecom', 'Satellite'),
('VoipServices', 'Telecom', 'VoIP'),
('CallCenter', 'Telecom', 'Call center'),
('MediaGroup Italia', 'Media', 'Media'),
('TVChannel', 'Media', 'Television'),
('RadioStation', 'Media', 'Radio'),
('NewsAgency', 'Media', 'News'),
('PublishingHouse', 'Media', 'Publishing'),
('PrintMedia', 'Media', 'Print'),
('DigitalMedia', 'Media', 'Digital media'),
('StreamingService', 'Media', 'Streaming'),
('PodcastNetwork', 'Media', 'Podcast'),
('SocialMedia Agency', 'Media', 'Social media'),
('InfluencerHub', 'Media', 'Influencers'),
('ContentCreator', 'Media', 'Content'),
('PRAgency', 'Media', 'PR'),
('Advertising Corp', 'Media', 'Advertising'),
('MarketingPro', 'Marketing', 'Marketing'),
('DigitalMarketing', 'Marketing', 'Digital marketing'),
('SEOAgency', 'Marketing', 'SEO'),
('EmailMarketing', 'Marketing', 'Email marketing'),
('SocialMarketing', 'Marketing', 'Social marketing'),
('BrandAgency', 'Marketing', 'Branding'),
('CreativeAgency', 'Marketing', 'Creative'),
('VideoProduction', 'Marketing', 'Video'),
('PhotoStudio', 'Marketing', 'Photo'),
('EventPlanner', 'Marketing', 'Events'),
('PhotoAgency', 'Marketing', 'Stock photos'),
('MarketResearch', 'Marketing', 'Research'),
('CustomerInsight', 'Marketing', 'Insights'),
('SalesForce Italia', 'Sales', 'Sales'),
('BusinessDev Group', 'Sales', 'Business development'),
('LeadGeneration', 'Sales', 'Leads'),
('SalesAutomation', 'Sales', 'Automation'),
('CRMSolutions', 'Sales', 'CRM'),
('ContactManagement', 'Sales', 'Contact management'),
('SalesTraining', 'Sales', 'Training'),
('DealFlow', 'Sales', 'Deal management'),
('InvoiceAutomation', 'Finance', 'Invoicing'),
('PaymentGateway', 'Finance', 'Payments'),
('ExpenseManagement', 'Finance', 'Expenses'),
('AccountingSoftware', 'Finance', 'Accounting'),
('BudgetPlanning', 'Finance', 'Budget'),
('FinancialPlanning', 'Finance', 'Planning'),
('TaxPreparation', 'Finance', 'Tax prep'),
('AuditServices', 'Finance', 'Audit'),
('ComplianceCheck', 'Finance', 'Compliance check');